name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-22.04
          - windows-2022

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.403
            7.0.100

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration Release --no-restore --no-incremental

      - name: Test
        run: dotnet test --configuration Release --no-restore --no-build --logger trx

      - name: Save Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: '**/TestResults/*.trx'

      - name: Collect NuGet Packages
        shell: pwsh
        run: |
          New-Item -Path nupkgs -ItemType Directory
          Get-ChildItem -Filter *.nupkg -Recurse | Copy-Item -Destination nupkgs

      - name: Save NuGet Packages
        uses: actions/upload-artifact@v3
        with:
          name: NuGet Packages
          path: 'nupkgs/*.nupkg'