name: Test Report
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
      - uses: phoenix-actions/test-reporting@v10
        id: test-report
        if: success()
        with:
          name: xUnit.NET Tests
          artifact: Test Results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx